<a href="https://colab.research.google.com/github/yangbingyi226/DataScience/blob/master/Linear_algebra_with_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Linear algebra with Numpy**

## **Manipulating matrices**

In [0]:
import numpy as np

In [0]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

In [3]:
A

matrix([[ 5,  6,  2],
        [ 4,  7, 19],
        [ 0,  3, 12]])

In [0]:
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])

In [5]:
B

matrix([[14, -2, 12],
        [ 4,  4,  5],
        [ 5,  5,  1]])

In [6]:
5 * A

matrix([[25, 30, 10],
        [20, 35, 95],
        [ 0, 15, 60]])

In [7]:
A ** 3

matrix([[ 557, 1284, 3356],
        [ 760, 2305, 6994],
        [ 288, 1074, 3519]])

In [8]:
A + B

matrix([[19,  4, 14],
        [ 8, 11, 24],
        [ 5,  8, 13]])

In [9]:
A - B

matrix([[ -9,   8, -10],
        [  0,   3,  14],
        [ -5,  -2,  11]])

In [10]:
A * B

matrix([[104,  24,  92],
        [179, 115, 102],
        [ 72,  72,  27]])

EXERCISE Compute $A ^ 2 - 2 A + 3$ with:


In [0]:
A = np.matrix([[1, -1],
               [2, 1]])

In [12]:
A ** 2 - 2 * A + 3

matrix([[0, 3],
        [3, 0]])

## **Solving Matrix equations**

In [0]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
b = np.matrix([[-1], [2], [1]])

In [14]:
x = np.linalg.solve(A, b)
x

matrix([[ 0.45736434],
        [-0.62790698],
        [ 0.24031008]])

In [15]:
A * x

matrix([[-1.],
        [ 2.],
        [ 1.]])

EXERCISE Compute the solutions to the matrix equation $Bx=b$ (using the $B$ defined earlier).

In [16]:
x = np.linalg.solve(B, b)
x

matrix([[-0.25892857],
        [ 0.40178571],
        [ 0.28571429]])

In [17]:
B * x

matrix([[-1.],
        [ 2.],
        [ 1.]])

## **Matrix inversion and determinants**

In [18]:
Ainv = np.linalg.inv(A)
Ainv

matrix([[-0.20930233,  0.51162791, -0.7751938 ],
        [ 0.37209302, -0.46511628,  0.6744186 ],
        [-0.09302326,  0.11627907, -0.08527132]])

In [19]:
A * Ainv

matrix([[ 1.00000000e+00,  4.99600361e-16, -4.71844785e-16],
        [ 1.38777878e-16,  1.00000000e+00, -2.63677968e-16],
        [ 1.11022302e-16,  1.11022302e-16,  1.00000000e+00]])

In [20]:
np.linalg.det(A)

-129.00000000000009

EXERCISE Compute the inverse and determinant of $B$ (defined previously).


In [21]:
Binv = np.linalg.inv(B)
Binv

matrix([[ 6.25000000e-02, -1.84523810e-01,  1.72619048e-01],
        [-6.25000000e-02,  1.36904762e-01,  6.54761905e-02],
        [-1.09511795e-17,  2.38095238e-01, -1.90476190e-01]])

In [22]:
B * Binv

matrix([[ 1.00000000e+00,  0.00000000e+00,  1.11022302e-16],
        [ 7.55253758e-19,  1.00000000e+00,  8.32667268e-17],
        [ 4.45599717e-17, -3.33066907e-16,  1.00000000e+00]])

In [23]:
np.linalg.det(B)

-336.0