<a href="https://colab.research.google.com/github/yangbingyi226/DataScience/blob/master/Linear_algebra_with_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Linear algebra with Numpy**

## **Manipulating matrices**

In [0]:
import numpy as np

In [0]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

In [4]:
A

matrix([[ 5,  6,  2],
        [ 4,  7, 19],
        [ 0,  3, 12]])

In [0]:
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])

In [6]:
B

matrix([[14, -2, 12],
        [ 4,  4,  5],
        [ 5,  5,  1]])

In [7]:
5 * A

matrix([[25, 30, 10],
        [20, 35, 95],
        [ 0, 15, 60]])

In [8]:
A ** 3

matrix([[ 557, 1284, 3356],
        [ 760, 2305, 6994],
        [ 288, 1074, 3519]])

In [9]:
A + B

matrix([[19,  4, 14],
        [ 8, 11, 24],
        [ 5,  8, 13]])

In [10]:
A - B

matrix([[ -9,   8, -10],
        [  0,   3,  14],
        [ -5,  -2,  11]])

In [11]:
A * B

matrix([[104,  24,  92],
        [179, 115, 102],
        [ 72,  72,  27]])

EXERCISE Compute $A ^ 2 - 2 A + 3$ with:


In [0]:
A = np.matrix([[1, -1],
               [2, 1]])

In [16]:
A ** 2 - 2 * A + 3

matrix([[0, 3],
        [3, 0]])

## **Solving Matrix equations**

In [0]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
b = np.matrix([[-1], [2], [1]])

In [18]:
x = np.linalg.solve(A, b)
x

matrix([[ 0.45736434],
        [-0.62790698],
        [ 0.24031008]])

In [19]:
A * x

matrix([[-1.],
        [ 2.],
        [ 1.]])

EXERCISE Compute the solutions to the matrix equation $Bx=b$ (using the $B$ defined earlier).